// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using coffeetime.Contexts;

#nullable disable

namespace coffeetime.Migrations
{
    [DbContext(typeof(ServerDbContext))]
    partial class ServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("coffeetime.Models.BatchTake", b =>
                {
                    b.Property<int>("BatchTakeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("TakenByUserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.HasKey("BatchTakeId");

                    b.HasIndex("BatchId", "CreatedAtUtc")
                        .HasDatabaseName("IX_take_batch_created");

                    b.HasIndex("TakenByUserId", "CreatedAtUtc")
                        .HasDatabaseName("IX_take_user_created");

                    b.ToTable("batch_takes", null, t =>
                        {
                            t.HasCheckConstraint("CK_batch_take_qty", "`Quantity` BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("coffeetime.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<uint>("ItemPrice")
                        .HasColumnType("int unsigned");

                    b.HasKey("ItemId");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("coffeetime.Models.PackageBatch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BatchCount")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<int>("RemainingCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("RoastedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("BatchId");

                    b.HasIndex("ItemId", "RoastedAtUtc")
                        .HasDatabaseName("IX_pkg_item_roasted");

                    b.HasIndex("OwnerUserId", "RemainingCount")
                        .HasDatabaseName("IX_pkg_owner_remaining");

                    b.ToTable("package_batches", null, t =>
                        {
                            t.HasCheckConstraint("CK_pkg_batch_count", "`BatchCount` BETWEEN 1 AND 30");

                            t.HasCheckConstraint("CK_pkg_remaining_count", "`RemainingCount` BETWEEN 0 AND 30");
                        });
                });

            modelBuilder.Entity("coffeetime.Models.UserCache", b =>
                {
                    b.Property<string>("UserObjectGuid")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("UserDisplayName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("UserObjectGuid");

                    b.ToTable("user_cache", (string)null);
                });

            modelBuilder.Entity("coffeetime.Models.BatchTake", b =>
                {
                    b.HasOne("coffeetime.Models.PackageBatch", "Batch")
                        .WithMany("Takes")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_batch_take_batch");

                    b.HasOne("coffeetime.Models.UserCache", "TakenByUser")
                        .WithMany("TakenBatches")
                        .HasForeignKey("TakenByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_batch_take_user");

                    b.Navigation("Batch");

                    b.Navigation("TakenByUser");
                });

            modelBuilder.Entity("coffeetime.Models.PackageBatch", b =>
                {
                    b.HasOne("coffeetime.Models.Item", "Item")
                        .WithMany("Batches")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_pkg_batch_item");

                    b.HasOne("coffeetime.Models.UserCache", "OwnerUser")
                        .WithMany("OwnedBatches")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_pkg_batch_owner");

                    b.Navigation("Item");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("coffeetime.Models.Item", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("coffeetime.Models.PackageBatch", b =>
                {
                    b.Navigation("Takes");
                });

            modelBuilder.Entity("coffeetime.Models.UserCache", b =>
                {
                    b.Navigation("OwnedBatches");

                    b.Navigation("TakenBatches");
                });
#pragma warning restore 612, 618
        }
    }
}
